import product1 from "@/assets/images/real/1.webp";
import product2 from "@/assets/images/real/2.webp";
import product3 from "@/assets/images/real/3.webp";
import product4 from "@/assets/images/real/4.webp";
import product5 from "@/assets/images/real/5.webp";
import product6 from "@/assets/images/real/6.webp";

export const products = [
	{
		id: 1,
		name: "Strawberry Semangka Lemon",
		tagline: "Sunshine in a bottle",
		category: "Infused Fruit Drinks",
		price: "Rp 20.000",
		color: "#F5A623",
		gradient: "from-[#F5A623] to-[#F7C948]",
		bgLight: "#FFF8E7",
		emoji: product1,
		ingredients: ["Orange", "Lemon", "Ginger"],
		badges: ["Best Seller", "100% Natural"],
		cal: "45 kcal",
		sugar: "8g",
	},
	{
		id: 2,
		name: "Berry Bloom",
		tagline: "Wild & wonderfully fresh",
		category: "Fruit Tea",
		price: "Rp 20.000",
		color: "#E8445A",
		gradient: "from-[#E8445A] to-[#FF7B8E]",
		bgLight: "#FFF0F2",
		emoji: product2,
		ingredients: ["Strawberry", "Raspberry", "Rose Hip"],
		badges: ["New", "Low Sugar"],
		cal: "38 kcal",
		sugar: "6g",
	},
	{
		id: 3,
		name: "Kiwi Zen",
		tagline: "Calm, cool, refreshed",
		category: "Chilled Fruit Drinks",
		price: "Rp 20.000",
		color: "#4CAF50",
		gradient: "from-[#4CAF50] to-[#8BC34A]",
		bgLight: "#F0F8F0",
		emoji: product3,
		ingredients: ["Kiwi", "Green Apple", "Mint"],
		badges: ["Vitamin C+", "Fresh Daily"],
		cal: "40 kcal",
		sugar: "7g",
	},
	{
		id: 4,
		name: "Mango Glow",
		tagline: "Tropical paradise sip",
		category: "Infused Fruit Drinks",
		price: "Rp 20.000",
		color: "#FF9800",
		gradient: "from-[#FF9800] to-[#FFB74D]",
		bgLight: "#FFF3E0",
		emoji: product4,
		ingredients: ["Mango", "Pineapple", "Turmeric"],
		badges: ["Immunity Boost"],
		cal: "52 kcal",
		sugar: "10g",
	},
	{
		id: 5,
		name: "Grape Mist",
		tagline: "Deep, dreamy refreshment",
		category: "Fruit Tea",
		price: "Rp 20.000",
		color: "#9C27B0",
		gradient: "from-[#9C27B0] to-[#CE93D8]",
		bgLight: "#F8F0FC",
		emoji: product5,
		ingredients: ["Grape", "Hibiscus", "Lavender"],
		badges: ["Antioxidant Rich"],
		cal: "35 kcal",
		sugar: "5g",
	},
	{
		id: 6,
		name: "Lemon Spark",
		tagline: "Zesty, alive, electric",
		category: "Chilled Fruit Drinks",
		price: "Rp 20.000",
		color: "#CDDC39",
		gradient: "from-[#CDDC39] to-[#DCE775]",
		bgLight: "#FAFDE7",
		emoji: product6,
		ingredients: ["Lemon", "Yuzu", "Basil"],
		badges: ["Zero Calories", "Detox"],
		cal: "12 kcal",
		sugar: "2g",
	},
];
