import bottleGlass from "@/assets/images/new/botol_kaca.png";
import bottlePlastic from "@/assets/images/new/botol_plastik.png";

export const products = [
	{
		id: 1,
		name: "FRUSH Botol Kaca",
		tagline: "Refreshing coconut meets tropical fruits",
		category: "Coconut Water",
		price: "Rp20.000",
		color: "#E8445A",
		gradient: "from-[#E8445A] to-[#FF7B8E]",
		bgLight: "#FFF0F2",
		emoji: bottleGlass,
		ingredients: ["Air Kelapa", "Strawberry", "Lemon", "Semangka"],
		badges: ["Best Seller", "No Basil Seeds"],
		cal: "52 kcal",
		sugar: "9g",
		volume: "350ml",
	},
	{
		id: 2,
		name: "FRUSH Botol Plastik",
		tagline: "Coconut goodness with a citrus twist",
		category: "Coconut Water",
		price: "Rp15.000",
		color: "#4CAF50",
		gradient: "from-[#4CAF50] to-[#8BC34A]",
		bgLight: "#F0F8F0",
		emoji: bottlePlastic,
		ingredients: ["Air Kelapa", "Bulir Jeruk", "Strawberry", "Biji Selasih"],
		badges: ["Affordable", "With Basil Seeds"],
		cal: "38 kcal",
		sugar: "7g",
		volume: "250ml",
	},
	// {
	// 	id: 3,
	// 	name: "Kiwi Zen",
	// 	tagline: "Calm, cool, refreshed",
	// 	category: "Chilled Fruit Drinks",
	// 	price: "Rp 20.000",
	// 	color: "#4CAF50",
	// 	gradient: "from-[#4CAF50] to-[#8BC34A]",
	// 	bgLight: "#F0F8F0",
	// 	emoji: product3,
	// 	ingredients: ["Kiwi", "Green Apple", "Mint"],
	// 	badges: ["Vitamin C+", "Fresh Daily"],
	// 	cal: "40 kcal",
	// 	sugar: "7g",
	// },
	// {
	// 	id: 4,
	// 	name: "Mango Glow",
	// 	tagline: "Tropical paradise sip",
	// 	category: "Infused Fruit Drinks",
	// 	price: "Rp 20.000",
	// 	color: "#FF9800",
	// 	gradient: "from-[#FF9800] to-[#FFB74D]",
	// 	bgLight: "#FFF3E0",
	// 	emoji: product4,
	// 	ingredients: ["Mango", "Pineapple", "Turmeric"],
	// 	badges: ["Immunity Boost"],
	// 	cal: "52 kcal",
	// 	sugar: "10g",
	// },
	// {
	// 	id: 5,
	// 	name: "Grape Mist",
	// 	tagline: "Deep, dreamy refreshment",
	// 	category: "Fruit Tea",
	// 	price: "Rp 20.000",
	// 	color: "#9C27B0",
	// 	gradient: "from-[#9C27B0] to-[#CE93D8]",
	// 	bgLight: "#F8F0FC",
	// 	emoji: product5,
	// 	ingredients: ["Grape", "Hibiscus", "Lavender"],
	// 	badges: ["Antioxidant Rich"],
	// 	cal: "35 kcal",
	// 	sugar: "5g",
	// },
	// {
	// 	id: 6,
	// 	name: "Lemon Spark",
	// 	tagline: "Zesty, alive, electric",
	// 	category: "Chilled Fruit Drinks",
	// 	price: "Rp 20.000",
	// 	color: "#CDDC39",
	// 	gradient: "from-[#CDDC39] to-[#DCE775]",
	// 	bgLight: "#FAFDE7",
	// 	emoji: product6,
	// 	ingredients: ["Lemon", "Yuzu", "Basil"],
	// 	badges: ["Zero Calories", "Detox"],
	// 	cal: "12 kcal",
	// 	sugar: "2g",
	// },
];
